ccflags-y += -I$(srctree)/drivers/android

obj-$(CONFIG_MILLET)	+= millet_core.o
obj-$(CONFIG_MILLET)	+= millet_pkg.o
obj-$(CONFIG_MILLET)	+= millet_hs.o
obj-$(CONFIG_MILLET)	+= binder_gki.o
obj-$(CONFIG_MILLET)	+= millet_binder.o
obj-$(CONFIG_MILLET)	+= millet_sig.o
obj-$(CONFIG_MILLET)	+= oem_cgroup.o
